# Generated by Django 6.0.3 on 2026-03-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='operation',
            field=models.CharField(choices=[('sale', 'Venta'), ('rent', 'Renta')], default='rent', max_length=10),
            preserve_default=False,
        ),
    ]
