# Generated by Django 6.0.3 on 2026-03-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='external_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
