# Generated by Django 6.0.3 on 2026-03-17 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_property_agent_property_antiquity_property_bedrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='semi_covered_area',
            field=models.FloatField(blank=True, null=True, verbose_name='Superficie semicubierta'),
        ),
        migrations.AlterField(
            model_name='property',
            name='antiquity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Antigüedad'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Baños'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dormitorios'),
        ),
        migrations.AlterField(
            model_name='property',
            name='covered_area',
            field=models.FloatField(blank=True, null=True, verbose_name='Superficie cubierta'),
        ),
        migrations.AlterField(
            model_name='property',
            name='half_bathrooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Medios Baños'),
        ),
        migrations.AlterField(
            model_name='property',
            name='land_area',
            field=models.FloatField(blank=True, null=True, verbose_name='Superficie terreno'),
        ),
        migrations.AlterField(
            model_name='property',
            name='parking',
            field=models.IntegerField(blank=True, null=True, verbose_name='Parqueaderos'),
        ),
        migrations.AlterField(
            model_name='property',
            name='rooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ambientes'),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_area',
            field=models.FloatField(blank=True, null=True, verbose_name='Superficie total'),
        ),
    ]
