# Generated by Django 6.0.3 on 2026-03-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_property_semi_covered_area_alter_property_antiquity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='expenses',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Expensas'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_floors',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pisos de la propiedad'),
        ),
    ]
