# Generated by Django 6.0.3 on 2026-03-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_property_expenses_property_property_floors'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.TextField(blank=True, null=True, verbose_name='Ubicación'),
        ),
    ]
