# Generated by Django 6.0.3 on 2026-03-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_property_latitude_property_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='offer_financing',
            field=models.BooleanField(blank=True, null=True, verbose_name='Ofrece financiamiento'),
        ),
        migrations.AddField(
            model_name='property',
            name='suitable_credit',
            field=models.BooleanField(blank=True, null=True, verbose_name='Apto crédito'),
        ),
        migrations.AddField(
            model_name='property',
            name='suitable_professional',
            field=models.BooleanField(blank=True, null=True, verbose_name='Apto profesional'),
        ),
    ]
