# Generated by Django 6.0.3 on 2026-03-17 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_property_offer_financing_property_suitable_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='extras',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
