# Generated by Django 6.0.3 on 2026-03-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_property_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='office_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='office_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='office_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
