# Generated by Django 6.0.3 on 2026-03-17 10:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_property_office_address_property_office_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='external_code',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='source',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='url',
            field=models.URLField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.UniqueConstraint(condition=models.Q(('external_code', None), _negated=True), fields=('source', 'external_code'), name='unique_source_external_code'),
        ),
    ]
