# Generated by Django 6.0.3 on 2026-03-17 11:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_property_uuid_alter_property_external_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
