# Generated by Django 6.0.3 on 2026-03-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_alter_property_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='currency',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
