# Generated by Django 6.0.3 on 2026-03-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_property_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='land',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Terreno'),
        ),
    ]
