# Generated by Django 6.0.3 on 2026-03-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_property_land'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='land',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Terreno'),
        ),
    ]
