# Generated by Django 6.0.3 on 2026-03-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_alter_property_land'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Año/mes de construccion'),
        ),
    ]
