# Generated by Django 6.0.3 on 2026-03-25 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_property_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='subtitle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
