# Generated by Django 6.0.3 on 2026-03-25 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0019_property_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='additional_costs',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
