# Generated by Django 6.0.3 on 2026-03-25 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_property_additional_costs'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
