# Generated by Django 6.0.3 on 2026-03-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0021_property_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price_negotiable',
            field=models.BooleanField(blank=True, null=True, verbose_name='Precio Negociable'),
        ),
    ]
