# Generated by Django 6.0.3 on 2026-03-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0022_property_price_negotiable'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='room_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
