# Generated by Django 6.0.3 on 2026-03-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0023_property_room_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='land_use',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
