# Generated by Django 6.0.3 on 2026-03-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0024_property_land_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de precio'),
        ),
    ]
