# Generated by Django 6.0.3 on 2026-03-25 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0025_property_price_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='price_negotiable',
        ),
    ]
