# Generated by Django 6.0.3 on 2026-03-14 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperstate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
