# Generated by Django 6.0.3 on 2026-03-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_scraperstate_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperstate',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='scraperstate',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
